language: objective-c

osx_image:
        - xcode8.2

xcode_project: Structure.xcodeproj

xcode_scheme:
        - Structure iOS
        - Structure Mac
        - Structure tvOS

xcode_sdk:
        - iphonesimulator10.2
        - macosx10.12
        - appletvsimulator10.1

matrix:
        exclude:
                - xcode_scheme: Structure iOS
                  xcode_sdk: macosx10.12
                - xcode_scheme: Structure iOS
                  xcode_sdk: appletvsimulator10.1
                - xcode_scheme: Structure Mac
                  xcode_sdk: iphonesimulator10.2
                - xcode_scheme: Structure Mac
                  xcode_sdk: appletvsimulator10.1
                - xcode_scheme: Structure tvOS
                  xcode_sdk: iphonesimulator10.2
                - xcode_scheme: Structure tvOS
                  xcode_sdk: macosx10.12

